# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ranking_pb2 as ranking__pb2


class RankingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAirlinesRankingByTicketPrice = channel.unary_unary(
                '/Ranking/GetAirlinesRankingByTicketPrice',
                request_serializer=ranking__pb2.AirlinesRankingByTicketPriceRequest.SerializeToString,
                response_deserializer=ranking__pb2.AirlinesRankingByTicketPriceResponse.FromString,
                )
        self.AddAirlinePrice = channel.unary_unary(
                '/Ranking/AddAirlinePrice',
                request_serializer=ranking__pb2.RankingInsertionRequest.SerializeToString,
                response_deserializer=ranking__pb2.RankingInsertionResponse.FromString,
                )
        self.DeleteTicket = channel.unary_unary(
                '/Ranking/DeleteTicket',
                request_serializer=ranking__pb2.RankingDeleteRequest.SerializeToString,
                response_deserializer=ranking__pb2.RankingDeleteResponse.FromString,
                )


class RankingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAirlinesRankingByTicketPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAirlinePrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RankingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAirlinesRankingByTicketPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAirlinesRankingByTicketPrice,
                    request_deserializer=ranking__pb2.AirlinesRankingByTicketPriceRequest.FromString,
                    response_serializer=ranking__pb2.AirlinesRankingByTicketPriceResponse.SerializeToString,
            ),
            'AddAirlinePrice': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAirlinePrice,
                    request_deserializer=ranking__pb2.RankingInsertionRequest.FromString,
                    response_serializer=ranking__pb2.RankingInsertionResponse.SerializeToString,
            ),
            'DeleteTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTicket,
                    request_deserializer=ranking__pb2.RankingDeleteRequest.FromString,
                    response_serializer=ranking__pb2.RankingDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Ranking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ranking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAirlinesRankingByTicketPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Ranking/GetAirlinesRankingByTicketPrice',
            ranking__pb2.AirlinesRankingByTicketPriceRequest.SerializeToString,
            ranking__pb2.AirlinesRankingByTicketPriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddAirlinePrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Ranking/AddAirlinePrice',
            ranking__pb2.RankingInsertionRequest.SerializeToString,
            ranking__pb2.RankingInsertionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Ranking/DeleteTicket',
            ranking__pb2.RankingDeleteRequest.SerializeToString,
            ranking__pb2.RankingDeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
