# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ranking.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rranking.proto\"5\n\x07\x41irline\x12\x14\n\x0c\x61irline_code\x18\x01 \x01(\t\x12\x14\n\x0c\x61irline_name\x18\x02 \x01(\t\"%\n#AirlinesRankingByTicketPriceRequest\"A\n$AirlinesRankingByTicketPriceResponse\x12\x19\n\x07\x61irline\x18\x01 \x03(\x0b\x32\x08.Airline2y\n\x07Ranking\x12n\n\x1fGetAirlinesRankingByTicketPrice\x12$.AirlinesRankingByTicketPriceRequest\x1a%.AirlinesRankingByTicketPriceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ranking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AIRLINE']._serialized_start=17
  _globals['_AIRLINE']._serialized_end=70
  _globals['_AIRLINESRANKINGBYTICKETPRICEREQUEST']._serialized_start=72
  _globals['_AIRLINESRANKINGBYTICKETPRICEREQUEST']._serialized_end=109
  _globals['_AIRLINESRANKINGBYTICKETPRICERESPONSE']._serialized_start=111
  _globals['_AIRLINESRANKINGBYTICKETPRICERESPONSE']._serialized_end=176
  _globals['_RANKING']._serialized_start=178
  _globals['_RANKING']._serialized_end=299
# @@protoc_insertion_point(module_scope)
