# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: visualization.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13visualization.proto\"k\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdeparture\x18\x02 \x01(\t\x12\x0f\n\x07\x61rrival\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\x14\n\x0c\x61irline_code\x18\x06 \x01(\t\"$\n\x07\x41irline\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\">\n\x0eTicketsRequest\x12\x16\n\x0e\x64\x65parturePlace\x18\x01 \x01(\t\x12\x14\n\x0c\x61rrivalPlace\x18\x02 \x01(\t\"+\n\x0fTicketsResponse\x12\x18\n\x07tickets\x18\x01 \x03(\x0b\x32\x07.Ticket\"%\n\x0e\x41irlineRequest\x12\x13\n\x0b\x61irlineCode\x18\x01 \x01(\t\",\n\x0f\x41irlineResponse\x12\x19\n\x07\x61irline\x18\x01 \x01(\x0b\x32\x08.Airline2q\n\rVisualization\x12/\n\nGetTickets\x12\x0f.TicketsRequest\x1a\x10.TicketsResponse\x12/\n\nGetAirline\x12\x0f.AirlineRequest\x1a\x10.AirlineResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'visualization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TICKET']._serialized_start=23
  _globals['_TICKET']._serialized_end=130
  _globals['_AIRLINE']._serialized_start=132
  _globals['_AIRLINE']._serialized_end=168
  _globals['_TICKETSREQUEST']._serialized_start=170
  _globals['_TICKETSREQUEST']._serialized_end=232
  _globals['_TICKETSRESPONSE']._serialized_start=234
  _globals['_TICKETSRESPONSE']._serialized_end=277
  _globals['_AIRLINEREQUEST']._serialized_start=279
  _globals['_AIRLINEREQUEST']._serialized_end=316
  _globals['_AIRLINERESPONSE']._serialized_start=318
  _globals['_AIRLINERESPONSE']._serialized_end=362
  _globals['_VISUALIZATION']._serialized_start=364
  _globals['_VISUALIZATION']._serialized_end=477
# @@protoc_insertion_point(module_scope)
