---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: database-visualization
    labels:
        app: database-visualization
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: database-visualization
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: database-visualization
        spec:
            containers:
                - name: database-visualization-container
                  image: alexandrefigueired0/database-visualization-container:latest
                  ports:
                      - containerPort: 50051
                  resources:
                      requests:
                          memory: "48Mi"
                          cpu: "20m"
                      limits:
                          memory: "64Mi"
                          cpu: "40m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: database-ranking
    labels:
        app: database-ranking
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: database-ranking
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: database-ranking
        spec:
            containers:
                - name: database-ranking-container
                  image: alexandrefigueired0/database-ranking-container:latest
                  ports:
                      - containerPort: 50052
                  resources:
                      requests:
                          memory: "48Mi"
                          cpu: "20m"
                      limits:
                          memory: "64Mi"
                          cpu: "40m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: forecast
    labels:
        app: forecast
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: forecast
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: forecast
        spec:
            containers:
                - name: forecast-container
                  image: alexandrefigueired0/forecast-container:latest
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "500m"
                      limits:
                          memory: "768Mi"
                          cpu: "750m"
                  readinessProbe:
                      httpGet:
                          path: /api/forecast/liveness-check
                          port: 8080
                      initialDelaySeconds: 120
                      periodSeconds: 10
                  livenessProbe:
                      httpGet:
                          path: /api/forecast/liveness-check
                          port: 8080
                      periodSeconds: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: management
    labels:
        app: management
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: management
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: management
        spec:
            containers:
                - name: management-container
                  image: alexandrefigueired0/management-container:latest
                  env:
                      - name: DATABASE_VISUALIZATION_HOST
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: DATABASE_VISUALIZATION_HOST
                      - name: DATABASE_RANKING_HOST
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: DATABASE_RANKING_HOST
                      - name: APP_SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: APP_SECRET_KEY
                      - name: AUTH0_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_DOMAIN
                      - name: AUTH0_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_CLIENT_ID
                      - name: AUTH0_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_CLIENT_SECRET
                  ports:
                      - containerPort: 8081
                  resources:
                      requests:
                          memory: "48Mi"
                          cpu: "100m"
                      limits:
                          memory: "64Mi"
                          cpu: "200m"
                  livenessProbe:
                      httpGet:
                          path: /api/management/liveness-check
                          port: 8081
                      initialDelaySeconds: 60
                      periodSeconds: 5
                  volumeMounts:
                      - name: secrets
                        mountPath: "/secrets"
                        readOnly: true
            volumes:
                - name: secrets
                  secret:
                      secretName: secret-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ranking
    labels:
        app: ranking
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: ranking
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: ranking
        spec:
            containers:
                - name: ranking-container
                  image: alexandrefigueired0/ranking-container:latest
                  env:
                      - name: DATABASE_RANKING_HOST
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: DATABASE_RANKING_HOST
                  ports:
                      - containerPort: 8082
                  resources:
                      requests:
                          memory: "64Mi" 
                          cpu: "20m"
                      limits:
                          memory: "128Mi"
                          cpu: "40m"
                  livenessProbe:
                      httpGet:
                          path: /api/ranking/liveness-check
                          port: 8082
                      initialDelaySeconds: 60
                      periodSeconds: 5
                  volumeMounts:
                      - name: secrets
                        mountPath: "/secrets"
                        readOnly: true
            volumes:
                - name: secrets
                  secret:
                      secretName: secret-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: recommendations
    labels:
        app: recommendations
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: recommendations
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: recommendations
        spec:
            containers:
                - name: recommendations-container
                  image: alexandrefigueired0/recommendations-container:1.0.4
                  ports:
                      - containerPort: 8083
                  env:
                      - name: APP_SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: APP_SECRET_KEY
                      - name: AUTH0_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_DOMAIN
                      - name: AUTH0_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_CLIENT_ID
                      - name: AUTH0_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_CLIENT_SECRET
                      - name: AUTH0_MANAGEMENT_TOKEN
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_MANAGEMENT_TOKEN
                  resources:
                      requests:
                          memory: "512Mi"
                          cpu: "500m"
                      limits:
                          memory: "768Mi"
                          cpu: "750m"
                  readinessProbe:
                      httpGet:
                          path: /api/recommendations/liveness-check
                          port: 8083
                      initialDelaySeconds: 120
                      periodSeconds: 10
                  livenessProbe:
                      httpGet:
                          path: /api/recommendations/liveness-check
                          port: 8083
                      periodSeconds: 80
                  volumeMounts:
                      - name: secrets
                        mountPath: "/secrets"
                        readOnly: true
            volumes:
                - name: secrets
                  secret:
                      secretName: secret-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: visualization
    labels:
        app: visualization
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: visualization
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: visualization
        spec:
            containers:
                - name: visualization-container
                  image: alexandrefigueired0/visualization-container:latest
                  env:
                      - name: DATABASE_VISUALIZATION_HOST
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: DATABASE_VISUALIZATION_HOST
                  ports:
                      - containerPort: 8084
                  resources:
                      requests:
                          memory: "64Mi" 
                          cpu: "20m"
                      limits:
                          memory: "128Mi"
                          cpu: "40m"
                  livenessProbe:
                      httpGet:
                          path: /api/visualization/liveness-check
                          port: 8084
                      initialDelaySeconds: 60
                      periodSeconds: 5
                  volumeMounts:
                      - name: secrets
                        mountPath: "/secrets"
                        readOnly: true
            volumes:
                - name: secrets
                  secret:
                      secretName: secret-prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: authentication
    labels:
        app: authentication
spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
        matchLabels:
            app: authentication
    strategy: 
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 33%
    template:
        metadata:
            labels:
                app: authentication
        spec:
            containers:
                - name: authentication-container
                  image: alexandrefigueired0/authentication-container:latest
                  env:
                      - name: APP_SECRET_KEY
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: APP_SECRET_KEY
                      - name: AUTH0_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_DOMAIN
                      - name: AUTH0_CLIENT_ID
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_CLIENT_ID
                      - name: AUTH0_CLIENT_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: secret-prod
                                key: AUTH0_CLIENT_SECRET
                  ports:
                      - containerPort: 8085
                  resources:
                      requests:
                          memory: "48Mi"
                          cpu: "100m"
                      limits:
                          memory: "64Mi"
                          cpu: "200m"
                  livenessProbe:
                      httpGet:
                          path: /api/authentication/liveness-check
                          port: 8085
                      initialDelaySeconds: 60
                      periodSeconds: 5
                  volumeMounts:
                      - name: secrets
                        mountPath: "/secrets"
                        readOnly: true
            volumes:
                - name: secrets
                  secret:
                      secretName: secret-prod
---
apiVersion: v1
kind: Service
metadata:
    name: database-ranking
spec:
    selector:
        app: database-ranking
    ports:
        - protocol: TCP
          port: 50052
          targetPort: 50052
---
apiVersion: v1
kind: Service
metadata:
    name: database-visualization
spec:
    selector:
        app: database-visualization
    ports:
        - protocol: TCP
          port: 50051
          targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
    name: forecast
spec:
    selector:
        app: forecast
    type: NodePort
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: management
spec:
    selector:
        app: management
    type: NodePort
    ports:
        - protocol: TCP
          port: 8081
          targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: ranking
spec:
    selector:
        app: ranking
    type: NodePort
    ports:
        - protocol: TCP
          port: 8082
          targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
    name: recommendations
spec:
    selector:
        app: recommendations
    type: NodePort
    ports:
        - protocol: TCP
          port: 8083
          targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
    name: visualization
spec:
    selector:
        app: visualization
    type: NodePort
    ports:
        - protocol: TCP
          port: 8084
          targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
    name: authentication
spec:
    selector:
        app: authentication
    ports:
        - protocol: TCP
          port: 8085
          targetPort: 8085
