scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
  
    - job_name: visualization
      scrape_interval: 5s
      static_configs:
        - targets: ['visualization:8084']

    - job_name: ranking
      scrape_interval: 5s
      static_configs:
        - targets: ['ranking:8082']

    - job_name: recommendations
      scrape_interval: 5s
      static_configs:
        - targets: ['recommendations:8083']

    - job_name: management
      scrape_interval: 5s
      static_configs:
        - targets: ['management:8081']

