scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['localhost:9090']
  
    - job_name: visualization
      scrape_interval: 5s
      static_configs:
        - targets: ['visualization:8084']

