#!/bin/bash

docker tag database-visualization-container anotherraqueldomingos/database-visualization-container
docker tag database-ranking-container anotherraqueldomingos/database-ranking-container 
docker tag forecast-container anotherraqueldomingos/forecast-container 
docker tag management-container anotherraqueldomingos/management-container 
docker tag recommendations-container anotherraqueldomingos/recommendations-container
docker tag visualization-container anotherraqueldomingos/visualization-container
docker tag ranking-container anotherraqueldomingos/ranking-container 
docker tag authentication-container anotherraqueldomingos/authentication-container

docker push anotherraqueldomingos/database-visualization-container
docker push anotherraqueldomingos/database-ranking-container
docker push anotherraqueldomingos/forecast-container
docker push anotherraqueldomingos/management-container
docker push anotherraqueldomingos/recommendations-container
docker push anotherraqueldomingos/visualization-container
docker push anotherraqueldomingos/ranking-container
docker push anotherraqueldomingos/authentication-container