# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ranking.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rranking.proto\"B\n\x13\x41irlineAveragePrice\x12\x14\n\x0c\x61irline_code\x18\x01 \x01(\t\x12\x15\n\raverage_price\x18\x02 \x01(\x02\"3\n\x0c\x41irlinePrice\x12\x14\n\x0c\x61irline_code\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\"%\n#AirlinesRankingByTicketPriceRequest\"N\n$AirlinesRankingByTicketPriceResponse\x12&\n\x08\x61irlines\x18\x01 \x03(\x0b\x32\x14.AirlineAveragePrice2\xaa\x01\n\x07Ranking\x12n\n\x1fGetAirlinesRankingByTicketPrice\x12$.AirlinesRankingByTicketPriceRequest\x1a%.AirlinesRankingByTicketPriceResponse\x12/\n\x0f\x41\x64\x64\x41irlinePrice\x12\r.AirlinePrice\x1a\r.AirlinePriceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ranking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AIRLINEAVERAGEPRICE']._serialized_start=17
  _globals['_AIRLINEAVERAGEPRICE']._serialized_end=83
  _globals['_AIRLINEPRICE']._serialized_start=85
  _globals['_AIRLINEPRICE']._serialized_end=136
  _globals['_AIRLINESRANKINGBYTICKETPRICEREQUEST']._serialized_start=138
  _globals['_AIRLINESRANKINGBYTICKETPRICEREQUEST']._serialized_end=175
  _globals['_AIRLINESRANKINGBYTICKETPRICERESPONSE']._serialized_start=177
  _globals['_AIRLINESRANKINGBYTICKETPRICERESPONSE']._serialized_end=255
  _globals['_RANKING']._serialized_start=258
  _globals['_RANKING']._serialized_end=428
# @@protoc_insertion_point(module_scope)
